export const REMOTE_METHODS = {
  process: {
    spawn: 'process/spawn',
    stdin: 'process/stdin',
    kill: 'process/kill',
    stdout: 'process/stdout',
    stderr: 'process/stderr',
    exit: 'process/exit',
  },
  fs: {
    browseDirectories: 'fs/browseDirectories',
    browseEntries: 'fs/browseEntries',
    writeFile: 'fs/writeFile',
    create: 'fs/create',
    delete: 'fs/delete',
    rename: 'fs/rename',
    copy: 'fs/copy',
    move: 'fs/move',
    list: 'fs/list',
    read: 'fs/read',
    exists: 'fs/exists',
    isDirectory: 'fs/isDirectory',
    statKind: 'fs/statKind',
  },
  git: {
    status: 'git/status',
    checkout: 'git/checkout',
    log: 'git/log',
    diff: 'git/diff',
    add: 'git/add',
    commit: 'git/commit',
    push: 'git/push',
    fetch: 'git/fetch',
    pull: 'git/pull',
    discardFile: 'git/discardFile',
    getRepoRoot: 'git/getRepoRoot',
    getProjectRoot: 'git/getProjectRoot',
    initRepo: 'git/initRepo',
    listBranches: 'git/listBranches',
    createWorktree: 'git/createWorktree',
    listWorktrees: 'git/listWorktrees',
    deleteWorktree: 'git/deleteWorktree',
    renameWorktree: 'git/renameWorktree',
    archiveWorktree: 'git/archiveWorktree',
  },
  watch: {
    start: 'watch/start',
    stop: 'watch/stop',
    snapshot: 'watch/snapshot',
  },
} as const;
